### ISSUE TITLE
[MDOAP-26] minimal pom IT is failing with Maven 3

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doap-plugin#67]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** opened **[MDOAP-26](https://issues.apache.org/jira/browse/MDOAP-26?redirect=false)** and commented

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-doap-plugin:1.1-SNAPSHOT:generate (default-cli) on project minimal: The parameters 'about' for goal org.apache.maven.plugins:maven-doap-plugin:1.1-SNAPSHOT:generate are missing or invalid -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-doap-plugin:1.1-SNAPSHOT:generate (default-cli) on project minimal: The parameters 'about' for goal org.apache.maven.plugins:maven-doap-plugin:1.1-SNAPSHOT:generate are missing or invalid
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:87)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:79)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:86)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:58)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:252)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:100)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:443)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:166)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginParameterException: The parameters 'about' for goal org.apache.maven.plugins:maven-doap-plugin:1.1-SNAPSHOT:generate are missing or invalid
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:518)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:471)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:99)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:144)
	... 19 more
```

---

**Affects:** 1.0

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

fixed in r985648
seems like depdency injection in Maven 3 (tested with beta-2, ie before Guice) is more strict about required parameters
