### ISSUE TITLE
[MDOAP-27] Generated files aren't useable with Jena

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doap-plugin#69]
**[Christian Mahnke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cmahnke)** opened **[MDOAP-27](https://issues.apache.org/jira/browse/MDOAP-27?redirect=false)** and commented

I'm generating a DOAP file for deployment, the resulting file isn't parseable by Jena, here the exception:

Caused by: com.hp.hpl.jena.rdf.model.LiteralRequiredException: Apache UGH metadata library
at com.hp.hpl.jena.rdf.model.impl.StatementImpl.getLiteral(StatementImpl.java:101)
at com.hp.hpl.jena.rdf.model.impl.StatementBase.getString(StatementBase.java:127)
at uk.ac.osswatch.simal.model.jena.Resource.getLiteralValue(Resource.java:198)
at uk.ac.osswatch.simal.model.jena.DoapResource.getName(DoapResource.java:77)
at uk.ac.osswatch.simal.wicket.panel.ProjectSummaryPanel.populatePage(ProjectSummaryPanel.java:83)
at uk.ac.osswatch.simal.wicket.panel.ProjectSummaryPanel.\<init>(ProjectSummaryPanel.java:65)
at uk.ac.osswatch.simal.wicket.UserHomePage.\<init>(UserHomePage.java:32)
... 32 more

The offending fragment of the DOAP file:

    
    
    
    
    <name rdf:resource="Apache UGH metadata library"/>

Note the spaces in the rdf:resource attribute. The Plugin should probably do a sanity check.

---

**Issue Links:**
- [MDOAP-24](https://issues.apache.org/jira/browse/MDOAP-24) programing-language, os and name properties should be an RDF literals, not a RDF resources.

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

MDOAP-24 fixed this issue and I added a validate parameter to validate the generated doap file using jena. Snapshot deployed.
